Update to 7.3.5
jboss-container-images/redhat-sso-7-openshift-image pull request #108
Opened 2019-10-25 14:11 UTC by ASzc

2019-10-25 16:35 UTC, iankko requested changes
Needs to wait till _EAP_725_\* tag is available.

2019-10-25 16:35 UTC, iankko commented on image.yaml
> +                  ref: EAP_724_1
Ditto here. It needs to be some _EAP_725_\* tag.

2019-11-07 15:06 UTC, ASzc commented
@iankko updated

2019-11-07 15:47 UTC, hmlnarik approved these changes

2019-11-07 15:47 UTC, hmlnarik commented
Thanks @ASzc

2019-11-07 15:47 UTC, merged