KEYCLOAK-16957 Update to EAP_736_CR1 and change SSO versions to 7.4.6
jboss-container-images/redhat-sso-7-openshift-image pull request #176
Opened 2021-03-08 17:48 UTC by ASzc

2021-03-09 09:00 UTC, iankko requested changes
Artifact / md5sum updates needed in ```image.yaml``` file yet.

2021-03-09 09:00 UTC, iankko commented on image.yaml
>              git:
@ASzc Thanks for the PR! The
```
- name: jboss-eap-7.3.5.GA-CR1-patch
       target: jboss-eap-7.3.5.GA-CR1-patch.zip
       md5: 921892c5a2234ca2bd09d5fd5ad1aad8
       url: http://$DOWNLOAD_SERVER/devel/candidates/jboss/eap/JBEAP-7.3.5.GA-CR1/jboss-eap-7.3.5.GA-CR1-patch.zip
```
section below should be updated to point to ```jboss-eap-7.3.6.GA-CR1-patch.zip``` below yet / instead (bump the artifact to ```jboss-eap-7.3.6.GA-CR1-patch.zip``` where necessary, and update the MD5 sum of the zip as appropriate).

The rest of the changes /lgtm AFAICT.

2021-03-09 09:01 UTC, iankko requested changes
See previous comment

2021-03-09 18:59 UTC, ASzc commented
Ok, thanks @iankko, I have updated the EAP patch referenced in image.yaml

2021-03-10 11:36 UTC, iankko commented
> Ok, thanks @iankko, I have updated the EAP patch referenced in image.yaml

This version /lgtm [1], thanks @ASzc !

--
[1]
```
[iankko@localhost tmp]$ diff -s /tmp/alexs_change.diff /tmp/7.4.6-expected-change 
Files /tmp/alexs_change.diff and /tmp/7.4.6-expected-change are identical
```

2021-03-10 11:36 UTC, iankko approved these changes
/lgtm

2021-03-10 13:22 UTC, pskopek approved these changes
looks good!

2021-03-10 13:47 UTC, merged