[CIAM-1035] IBM Semeru JDK is not installed properly. Also remove JDK 8 since not needed anymore
jboss-container-images/redhat-sso-7-openshift-image pull request #205
Opened 2021-10-14 08:59 UTC by drichtarik

@iankko @levivic

2021-10-14 09:13 UTC, iankko commented on modules/sso/sso-rm-openjdk/11/configure.sh
> +if rpm -q ibm-semeru-open-11-jdk; then
@drichtarik I would probably keep this covering both cases. IOW to remove `openjdk-devel` if either `ibm-semeru-open-11-jdk` or `java-11-openj9-devel` are present.

Though `java-11-openj9-devel` can't be installed at the moment, this is just convenience approach for the future, if / once we would switch the OpenJ9 overrides module to start installing `java-11-openj9-devel` again.

@levivic -^ WDYT should we cover both possibilities?

2021-10-14 09:19 UTC, iankko reviewed
@drichtarik Thanks for the change. One small nitpick (to cover both OpenJ9 & IBM Semeru cases in `sso-rm-jdk` module) yet, but rest of the changes LGTM.

2021-10-14 09:35 UTC, iankko approved these changes
The latest version LGTM. Thx Denis!

2021-10-14 09:35 UTC, iankko commented on modules/sso/sso-rm-openjdk/11/configure.sh
> +if rpm -q ibm-semeru-open-11-jdk; then
Checking for both variants is covered in latest patch form.

2021-10-14 18:23 UTC, drichtarik commented
Run 234 was finally successful. @levivic told me he will let us know if the correct java was used. I provided him with the scratch build done by this PR.

2021-10-15 07:47 UTC, iankko requested changes
See @levivic 's comment above. @drichtarik That openjdk module installation needs to be removed from the eap module definition.

2021-10-26 12:24 UTC, drichtarik commented
@iankko run 263 was successful with the latest update

2021-11-02 12:23 UTC, levivic commented
@drichtarik  this looks good to me.

2021-11-02 12:36 UTC, merged