Revert back patch changes and change the eap 7.3.10 link
jboss-container-images/redhat-sso-7-openshift-image pull request #228
Opened 2022-01-17 17:24 UTC by drichtarik

@iankko

2022-01-17 17:43 UTC, iankko requested changes
Two changes needed yet (see comments). The rest of the changes LGTM

2022-01-17 17:43 UTC, iankko commented on image.yaml
> +                  ref: EAP_7310_CR1
@drichtarik I would use [EAP_7310_CR2](https://github.com/jboss-container-images/jboss-eap-7-image/releases/tag/EAP_7310_CR2) here.

2022-01-17 17:43 UTC, iankko commented on image.yaml
> +       url: http://$DOWNLOAD_SERVER/devel/released/JBoss-middleware/eap7/7.3.10/jboss-eap-7.3.10-patch.zip
@drichtarik The link can't have both `devel` & `released/`. Drop the `devel/` from it:

```
 curl -I http://$DOWNLOAD_SERVER/devel/released/JBoss-middleware/eap7/7.3.10/jboss-eap-7.3.10-patch.zip
HTTP/1.1 404 Not Found
Date: Mon, 17 Jan 2022 17:35:24 GMT
Server: Apache
Content-Type: text/html; charset=iso-8859-1
```
compared to (working one):
```
$ curl -I http://$DOWNLOAD_SERVER/released/JBoss-middleware/eap7/7.3.10/jboss-eap-7.3.10-patch.zip
HTTP/1.1 200 OK
Date: Mon, 17 Jan 2022 17:36:24 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips
Last-Modified: Wed, 15 Dec 2021 13:11:17 GMT
ETag: "9e1bb9c-5d32f0a94b4d4"
Accept-Ranges: bytes
Content-Length: 165788572
Content-Type: application/zip
```
The md5sum is OK.

2022-01-17 20:02 UTC, drichtarik commented
Should be fixed now

2022-01-18 11:28 UTC, iankko approved these changes
This version LGTM. Thanks Denis

2022-01-18 11:32 UTC, merged